# With OnehotEncoding

In [1]:
import pandas as pd
import tensorflow as tf
data = pd.read_excel('E:/Sales (2).xlsx')

In [2]:
data.head()

Billing Date  Customer  Material Number  Material Group     Qty UoM  \
0   2019-04-01  10000519           300216        10000001   960.0  KG   
1   2019-04-01  10002347           300204        10000001    82.0  KG   
2   2019-04-01  10002347           300236        10000001  4000.0  KG   
3   2019-04-01  10002347           300236        10000001  5000.0  KG   
4   2019-04-01  10002347           300236        10000001  5500.0  KG   

   Net Value in Doc Currency  
0                   67200.00  
1                    3717.06  
2                  146720.00  
3                  183400.00  
4                  201740.00

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152683 entries, 0 to 152682
Data columns (total 7 columns):
 #   Column                     Non-Null Count   Dtype         
---  ------                     --------------   -----         
 0   Billing Date               152683 non-null  datetime64[ns]
 1   Customer                   152683 non-null  int64         
 2   Material Number            152683 non-null  int64         
 3   Material Group             152683 non-null  int64         
 4   Qty                        152683 non-null  float64       
 5   UoM                        152683 non-null  object        
 6   Net Value in Doc Currency  152683 non-null  float64       
dtypes: datetime64[ns](1), float64(2), int64(3), object(1)
memory usage: 8.2+ MB


In [4]:
data.drop(['Customer' , 'Material Number' , 'Qty' , 'UoM'] , axis = 1 , inplace = True)

In [5]:
data.columns = ['Date' , 'Material' , 'Sales']

In [6]:
data['Date'] = data['Date'].apply(lambda x: str(x)[:-9])  
data = data.groupby(['Date' , 'Material'])['Sales'].sum().reset_index()
print(len(data))
data.head()

3265


Date  Material       Sales
0  2019-04-01  10000001   602777.06
1  2019-04-01  10000002   178063.20
2  2019-04-01  10000003   216684.00
3  2019-04-01  10000005  5151641.82
4  2019-04-01  10000007  2580483.11

In [7]:
data['Material'].value_counts()

10000001    91
10000019    91
10000007    91
10000009    91
10000011    91
10000013    91
10000015    91
10000017    91
10000021    91
10000040    91
10000023    91
10000029    91
10000031    91
10000033    91
10000035    91
10000037    91
10000005    91
10000039    91
10000020    91
10000008    91
10000010    91
10000034    91
10000012    91
10000030    91
10000028    91
10000014    91
10000024    91
10000022    91
10000036    91
10000018    91
10000016    91
10000027    89
10000025    89
10000002    70
10000003    63
10000004    62
10000026    56
10000006     7
10000032     6
10000038     2
Name: Material, dtype: int64

In [8]:
lister = data['Material'].unique()
print(lister)

[10000001 10000002 10000003 10000005 10000007 10000008 10000009 10000010
 10000011 10000012 10000013 10000014 10000015 10000016 10000017 10000018
 10000019 10000020 10000021 10000022 10000023 10000024 10000025 10000027
 10000028 10000029 10000030 10000031 10000033 10000034 10000035 10000036
 10000037 10000039 10000040 10000026 10000004 10000038 10000032 10000006]


In [9]:
import numpy as np
for i in lister:
    data.insert(1 , str(i) , np.zeros(len(data)))

In [10]:
data.head()

Date  10000006  10000032  10000038  10000004  10000026  10000040  \
0  2019-04-01       0.0       0.0       0.0       0.0       0.0       0.0   
1  2019-04-01       0.0       0.0       0.0       0.0       0.0       0.0   
2  2019-04-01       0.0       0.0       0.0       0.0       0.0       0.0   
3  2019-04-01       0.0       0.0       0.0       0.0       0.0       0.0   
4  2019-04-01       0.0       0.0       0.0       0.0       0.0       0.0   

   10000039  10000037  10000036  ...  10000010  10000009  10000008  10000007  \
0       0.0       0.0       0.0  ...       0.0       0.0       0.0       0.0   
1       0.0       0.0       0.0  ...       0.0       0.0       0.0       0.0   
2       0.0       0.0       0.0  ...       0.0       0.0       0.0       0.0   
3       0.0       0.0       0.0  ...       0.0       0.0       0.0       0.0   
4       0.0       0.0       0.0  ...       0.0       0.0       0.0       0.0   

   10000005  10000003  10000002  10000001  Material       Sales  
0       0.0       0.0       0.0       0.0  10000001   602777.06  
1       0.0       0.0       0.0       0.0  10000002   178063.20  
2       0.0       0.0       0.0       0.0  10000003   216684.00  
3       0.0       0.0       0.0       0.0  10000005  5151641.82  
4       0.0       0.0       0.0       0.0  10000007  2580483.11  

[5 rows x 43 columns]

In [11]:
print(str(data.loc[0 , 'Material']))
print(data.loc[0 , 'Sales'])

for i in range(len(data)):
    x = str(data.loc[i , 'Material'])
    data.loc[i , x] = data.loc[i , 'Sales']
    
data.head()

10000001
602777.06


Date  10000006  10000032  10000038  10000004  10000026  10000040  \
0  2019-04-01       0.0       0.0       0.0       0.0       0.0       0.0   
1  2019-04-01       0.0       0.0       0.0       0.0       0.0       0.0   
2  2019-04-01       0.0       0.0       0.0       0.0       0.0       0.0   
3  2019-04-01       0.0       0.0       0.0       0.0       0.0       0.0   
4  2019-04-01       0.0       0.0       0.0       0.0       0.0       0.0   

   10000039  10000037  10000036  ...  10000010  10000009  10000008  \
0       0.0       0.0       0.0  ...       0.0       0.0       0.0   
1       0.0       0.0       0.0  ...       0.0       0.0       0.0   
2       0.0       0.0       0.0  ...       0.0       0.0       0.0   
3       0.0       0.0       0.0  ...       0.0       0.0       0.0   
4       0.0       0.0       0.0  ...       0.0       0.0       0.0   

     10000007    10000005  10000003  10000002   10000001  Material       Sales  
0        0.00        0.00       0.0       0.0  602777.06  10000001   602777.06  
1        0.00        0.00       0.0  178063.2       0.00  10000002   178063.20  
2        0.00        0.00  216684.0       0.0       0.00  10000003   216684.00  
3        0.00  5151641.82       0.0       0.0       0.00  10000005  5151641.82  
4  2580483.11        0.00       0.0       0.0       0.00  10000007  2580483.11  

[5 rows x 43 columns]

In [12]:
lister = list(map(str, lister))
lister.append('Sales')
print(lister)

['10000001', '10000002', '10000003', '10000005', '10000007', '10000008', '10000009', '10000010', '10000011', '10000012', '10000013', '10000014', '10000015', '10000016', '10000017', '10000018', '10000019', '10000020', '10000021', '10000022', '10000023', '10000024', '10000025', '10000027', '10000028', '10000029', '10000030', '10000031', '10000033', '10000034', '10000035', '10000036', '10000037', '10000039', '10000040', '10000026', '10000004', '10000038', '10000032', '10000006', 'Sales']


In [13]:
dm = data.groupby(['Date'])[lister].sum().reset_index()
dm.head()

Date    10000001   10000002  10000003    10000005    10000007  \
0  2019-04-01   602777.06   178063.2  216684.0  5151641.82  2580483.11   
1  2019-04-02   274240.00  2291000.0       0.0  4483264.36  2084867.32   
2  2019-04-03  1553522.60        0.0  107945.0  5750702.46  2585973.88   
3  2019-04-04  3843352.00    25437.6       0.0  5840138.40  2979784.80   
4  2019-04-05  4205908.00  1657290.0  212734.2  5600504.71  2366882.52   

     10000008   10000009   10000010   10000011  ...    10000036    10000037  \
0  2313731.83  726852.28  170344.82   77752.85  ...  1036169.01  3025013.80   
1  2318207.75  696174.58  180734.52  369328.01  ...   996406.24  3078471.84   
2  2909510.91  876963.24  438047.24  123922.59  ...  1423093.67  3607853.01   
3  2733588.27  770636.24  251737.51   68695.09  ...  1025335.74  3646552.61   
4  2602766.12  709088.41  630929.56   50410.65  ...  1060735.39  3405518.35   

    10000039   10000040  10000026   10000004  10000038  10000032  10000006  \
0  355094.46  233812.11       0.0       0.00       0.0       0.0       0.0   
1  328726.67  358724.23       0.0       0.00       0.0       0.0       0.0   
2  343502.11  286247.69   49419.6       0.00       0.0       0.0       0.0   
3  669379.13  217040.86  138109.8       0.00       0.0       0.0       0.0   
4  284880.90  390380.06  149912.5  811534.88       0.0       0.0       0.0   

         Sales  
0  50648642.57  
1  49429212.10  
2  58869847.96  
3  60938957.87  
4  60422859.61  

[5 rows x 42 columns]

In [14]:
HORIZON = 1 # predict 1 step at a time
WINDOW_SIZE = 7 # use a week worth of timesteps to predict the horizon

In [15]:
lister.remove('Sales')
print(lister)

['10000001', '10000002', '10000003', '10000005', '10000007', '10000008', '10000009', '10000010', '10000011', '10000012', '10000013', '10000014', '10000015', '10000016', '10000017', '10000018', '10000019', '10000020', '10000021', '10000022', '10000023', '10000024', '10000025', '10000027', '10000028', '10000029', '10000030', '10000031', '10000033', '10000034', '10000035', '10000036', '10000037', '10000039', '10000040', '10000026', '10000004', '10000038', '10000032', '10000006']


In [16]:
def get_windowed_indexes(x , window_size , horizon):
    # 1. Create a window of specific window_size (add the horizon on the end for later labelling)
    window_step = np.expand_dims(np.arange(window_size+horizon), axis=0)
    # print(f"Window step:\n {window_step}")

    # 2. Create a 2D array of multiple window steps (minus 1 to account for 0 indexing)
    window_indexes = window_step + np.expand_dims(np.arange(len(x)-(window_size+horizon-1)), axis=0).T
    
    return window_indexes

In [17]:
indexes = get_windowed_indexes(dm , WINDOW_SIZE , HORIZON)
print(indexes.shape)

(84, 8)


In [18]:
full_windows = []
# full_labels = []
for i in indexes:
    for j in range(len(lister)):
        win = dm[lister[j]][i]
#         win , label = win[:-1] , win[-1:]
        win = win.to_numpy()
        window = np.insert(win , 0 , lister[j])
        full_windows.append(window.tolist())
#         full_labels.append(label.to_list())
print(full_windows[:3])
# print(full_labels[:3])

[[10000001.0, 602777.06, 274240.0, 1553522.6, 3843352.0, 4205908.0, 6881344.0, 6101444.0, 1329717.0], [10000002.0, 178063.2, 2291000.0, 0.0, 25437.6, 1657290.0, 1840.0, 1800.0, 17000.0], [10000003.0, 216684.0, 0.0, 107945.0, 0.0, 212734.2, 0.0, 136696.8, 57740.25]]


In [21]:
# import tensorflow as tf
# max_windows_val = tf.math.reduce_max(full_windows)
# min_windows_val = tf.math.reduce_min(full_windows)
# range_windows = max_windows_val - min_windows_val

# max_labels_val = tf.math.reduce_max(full_labels)
# min_labels_val = tf.math.reduce_min(full_labels)
# range_labels = max_labels_val - min_labels_val

In [22]:
# full_windows = full_windows / range_windows
# full_labels = full_labels / range_labels
# print(full_windows[:3])
# print(full_labels[:3])

In [19]:
dataframe = pd.DataFrame(full_windows , columns = ['Material' , 'Day-1' , 'Day-2' , 'Day-3' , 'Day-4' , 'Day-5' , 'Day-6' , 'Day-7' , 'Prediction'])
dataframe.head()

Material       Day-1       Day-2       Day-3      Day-4       Day-5  \
0  10000001.0   602777.06   274240.00  1553522.60  3843352.0  4205908.00   
1  10000002.0   178063.20  2291000.00        0.00    25437.6  1657290.00   
2  10000003.0   216684.00        0.00   107945.00        0.0   212734.20   
3  10000005.0  5151641.82  4483264.36  5750702.46  5840138.4  5600504.71   
4  10000007.0  2580483.11  2084867.32  2585973.88  2979784.8  2366882.52   

        Day-6       Day-7  Prediction  
0  6881344.00  6101444.00  1329717.00  
1     1840.00     1800.00    17000.00  
2        0.00   136696.80    57740.25  
3  5056658.57  4572115.32  4654375.08  
4  2361125.47  2236869.93  2330754.56

In [20]:
try_1 = pd.concat([dataframe , pd.get_dummies(dataframe['Material'], prefix='Material')],axis=1)
try_1.drop(['Material'],axis=1, inplace=True)
try_1.head()

Day-1       Day-2       Day-3      Day-4       Day-5       Day-6  \
0   602777.06   274240.00  1553522.60  3843352.0  4205908.00  6881344.00   
1   178063.20  2291000.00        0.00    25437.6  1657290.00     1840.00   
2   216684.00        0.00   107945.00        0.0   212734.20        0.00   
3  5151641.82  4483264.36  5750702.46  5840138.4  5600504.71  5056658.57   
4  2580483.11  2084867.32  2585973.88  2979784.8  2366882.52  2361125.47   

        Day-7  Prediction  Material_10000001.0  Material_10000002.0  ...  \
0  6101444.00  1329717.00                    1                    0  ...   
1     1800.00    17000.00                    0                    1  ...   
2   136696.80    57740.25                    0                    0  ...   
3  4572115.32  4654375.08                    0                    0  ...   
4  2236869.93  2330754.56                    0                    0  ...   

   Material_10000031.0  Material_10000032.0  Material_10000033.0  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   Material_10000034.0  Material_10000035.0  Material_10000036.0  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   Material_10000037.0  Material_10000038.0  Material_10000039.0  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   Material_10000040.0  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  

[5 rows x 48 columns]

### Split Data for RandomForest

In [20]:
def train_test_split(X , y , split_size = 0.2):
    length = int((1 - split_size) * len(X))
    train_data , train_label = X[:length] , y[:length]
    test_data , test_label = X[length:] , y[length:]
    return train_data , test_data , train_label , test_label

In [21]:
train_data , test_data , train_label , test_label = train_test_split(try_1.drop('Prediction' , axis = 1) , try_1['Prediction'])
train_data[:5] , train_label[:5]

(        Day-1       Day-2       Day-3      Day-4       Day-5       Day-6  \
 0   602777.06   274240.00  1553522.60  3843352.0  4205908.00  6881344.00   
 1   178063.20  2291000.00        0.00    25437.6  1657290.00     1840.00   
 2   216684.00        0.00   107945.00        0.0   212734.20        0.00   
 3  5151641.82  4483264.36  5750702.46  5840138.4  5600504.71  5056658.57   
 4  2580483.11  2084867.32  2585973.88  2979784.8  2366882.52  2361125.47   
 
         Day-7  Material_10000001.0  Material_10000002.0  Material_10000003.0  \
 0  6101444.00                    1                    0                    0   
 1     1800.00                    0                    1                    0   
 2   136696.80                    0                    0                    1   
 3  4572115.32                    0                    0                    0   
 4  2236869.93                    0                    0                    0   
 
    ...  Material_10000031.0  Material_10000032.

## Random Forest

In [22]:
from sklearn.ensemble import RandomForestRegressor

random_forest_model = RandomForestRegressor(n_estimators = 100, random_state = 0).fit(train_data , train_label)

In [23]:
y_pred = random_forest_model.predict(test_data)

### Error handler

In [24]:
def errors(y_true , y_pred):
    y_true = tf.cast(y_true, dtype=tf.float32)
    y_pred = tf.cast(y_pred, dtype=tf.float32)
    y_new = np.abs(y_true - y_pred)
    median = np.median(y_new)
    mae = tf.keras.metrics.mean_absolute_error(y_true, y_pred)
    mse = tf.keras.metrics.mean_squared_error(y_true, y_pred) # puts and emphasis on outliers (all errors get squared)
    rmse = tf.sqrt(mse)
    mape = tf.keras.metrics.mean_absolute_percentage_error(y_true, y_pred)
    y_new2 = np.zeros(len(y_new))
    for i in range(len(y_new)):
        if(y_true[i] != 0):
            y_new2[i] = y_new[i] / y_true[i] * 100
    median_per = np.median(y_new2)
    mean_per = np.mean(y_new2)
    maxi = np.amax(y_new2)
    mini = np.amin(y_new2)
    
    return {'MAE: ' : mae.numpy() , 'MSE' : mse.numpy() , 'RMSE' : rmse.numpy() ,
            'MAPE' : mape.numpy() , 'Median' : median , '% error wrt median' : median_per , '% error wrt mean' : mean_per , 
           'Min% Error' : mini , 'Max% Error' : maxi}

In [25]:
test_label[:5] , y_pred[:5]

(2688      88287.00
 2689    4399137.02
 2690    1007368.34
 2691    3480342.96
 2692    2186020.23
 Name: Prediction, dtype: float64,
 array([ 165734.4024, 3808046.3818,  980483.5034, 3100322.7774,
         774772.8538]))

In [26]:
random_forest_error = errors(tf.squeeze(test_label) , y_pred)
print(random_forest_error)

{'MAE: ': 325523.56, 'MSE': 504076140000.0, 'RMSE': 709983.2, 'MAPE': 6736443300000.0, 'Median': 122858.97, '% error wrt median': 12.223315238952637, '% error wrt mean': 67.80606888112379, 'Min% Error': 0.0, 'Max% Error': 10775.12109375}


## Linear Regression

In [27]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression().fit(train_data , train_label)

In [28]:
y_pred = linear_model.predict(test_data)

In [29]:
linear_error = errors(tf.squeeze(test_label) , y_pred)
print(linear_error)

{'MAE: ': 380650.16, 'MSE': 597689700000.0, 'RMSE': 773103.94, 'MAPE': 6064724000000.0, 'Median': 170755.69, '% error wrt median': 17.3764705657959, '% error wrt mean': 54.25746817816461, 'Min% Error': 0.0, 'Max% Error': 4515.06591796875}


## KNN regressor

In [30]:
from sklearn.neighbors import KNeighborsRegressor

knn_model = KNeighborsRegressor().fit(train_data , train_label)

In [31]:
y_pred = knn_model.predict(test_data)

In [32]:
knn_error = errors(tf.squeeze(test_label) , y_pred)
print(knn_error)

{'MAE: ': 336379.78, 'MSE': 547696480000.0, 'RMSE': 740065.2, 'MAPE': 7767849400000.0, 'Median': 129801.28, '% error wrt median': 13.562328338623047, '% error wrt mean': 64.83044506850862, 'Min% Error': 0.0, 'Max% Error': 7342.72216796875}


## Decision Tree

In [33]:
from sklearn.tree import DecisionTreeRegressor
decision_model = DecisionTreeRegressor().fit(train_data , train_label)

In [34]:
y_pred = decision_model.predict(test_data)

In [35]:
decision_error = errors(tf.squeeze(test_label) , y_pred)
print(decision_error)

{'MAE: ': 468124.16, 'MSE': 1045385700000.0, 'RMSE': 1022441.06, 'MAPE': 5603156600000.0, 'Median': 151400.06, '% error wrt median': 17.467209815979004, '% error wrt mean': 121.92656634527347, 'Min% Error': 0.0, 'Max% Error': 37454.59765625}


## Data preparation for Tensor

In [36]:
# Convert data into numpy so that tensorflow can make appropriate changes
full_window = try_1.drop('Prediction' , axis = 1).to_numpy()
full_label = try_1['Prediction'].to_numpy()
full_window[:3] , full_label[:3]

(array([[6.0277706e+05, 2.7424000e+05, 1.5535226e+06, 3.8433520e+06,
         4.2059080e+06, 6.8813440e+06, 6.1014440e+06, 1.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [1.7806320e+05, 2.2910000e+06, 0.0000000e+00, 2.5437600e+04,
         1.6572900e+06, 1.8400000e+03, 1.8000000e+03, 0.0000000e+00,
         1.0000000e+00, 0.0000000e+00, 0.0000000

In [37]:
train_data , test_data , train_label , test_label = train_test_split(full_window , full_label)
test_data[:3] , test_label[:3]

(array([[9.54748400e+04, 3.69052430e+05, 1.46352920e+05, 1.93992620e+05,
         1.10628290e+05, 5.36643600e+04, 7.32431900e+04, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [4.09295942e+06, 4.27619482e+06, 2.89048911e+06, 4.36516361e+06,
         4.55561279e+06, 3.74795096e+06, 4.43930803e+06, 0.0000000

In [38]:
import os

# Create a function to implement a ModelCheckpoint callback with a specific filename 
def create_model_checkpoint(model_name, save_path="model_experiments"):
    return tf.keras.callbacks.ModelCheckpoint(filepath=os.path.join(save_path, model_name), # create filepath to save model
                                            verbose=0, # only output a limited amount of text
                                            save_best_only=True) # save only the best model to file

## Tiny Model

In [39]:
from tensorflow.keras import layers

tiny_model = tf.keras.Sequential([
    layers.Lambda(lambda x: tf.expand_dims(x, axis=1)) ,
    layers.GRU(100 , activation = 'relu') , 
    layers.Dense(1 , activation = 'relu')
] , name = 'Tiny_Model')

tiny_model.compile(loss = tf.keras.losses.mae , optimizer = tf.keras.optimizers.Adam())

tiny_model.fit(x = train_data , y = train_label , epochs = 100 , batch_size = 128 , 
               validation_data = (test_data , test_label) , 
               callbacks=[create_model_checkpoint(model_name=tiny_model.name)])

Epoch 1/100
21/21 [==============================] - 4s 56ms/step - loss: 1391106.3750 - val_loss: 1280156.7500
INFO:tensorflow:Assets written to: model_experiments\Tiny_Model\assets
Epoch 2/100
21/21 [==============================] - 0s 5ms/step - loss: 590073.3125 - val_loss: 322907.3438
INFO:tensorflow:Assets written to: model_experiments\Tiny_Model\assets
Epoch 3/100
21/21 [==============================] - 0s 7ms/step - loss: 281580.0625 - val_loss: 328089.0625
Epoch 4/100
21/21 [==============================] - 0s 7ms/step - loss: 264800.2812 - val_loss: 303672.8750
INFO:tensorflow:Assets written to: model_experiments\Tiny_Model\assets
Epoch 5/100
21/21 [==============================] - 0s 6ms/step - loss: 253122.8594 - val_loss: 313490.4375
Epoch 6/100
21/21 [==============================] - 0s 5ms/step - loss: 254879.3750 - val_loss: 310468.3438
Epoch 7/100
21/21 [==============================] - 0s 6ms/step - loss: 251919.5469 - val_loss: 308408.0312
Epoch 8/100
21/21 [==

In [40]:
def make_preds(model, input_data):
    forecast = model.predict(input_data)
    return tf.squeeze(forecast) # return 1D array of predictions

In [41]:
tiny_model = tf.keras.models.load_model("model_experiments/Tiny_Model/")
tiny_model.evaluate(test_data , test_label)

21/21 [==============================] - 0s 1ms/step - loss: 288653.1562


288653.15625

In [42]:
tiny_model_preds = make_preds(tiny_model , test_data)
tiny_model_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([  91930.12, 4379104.5 , 1041325.56, 3238549.5 ,  593057.2 ,
        146896.47, 2380032.5 , 2657306.  , 3210694.8 , 2018606.8 ],
      dtype=float32)>

In [43]:
tiny_model_error = errors(test_label , tiny_model_preds)
print(tiny_model_error)

{'MAE: ': 288653.1, 'MSE': 448565540000.0, 'RMSE': 669750.4, 'MAPE': 4344638300000.0, 'Median': 127747.31, '% error wrt median': 11.82497787475586, '% error wrt mean': 35.671258092913334, 'Min% Error': 0.0, 'Max% Error': 2126.05517578125}


## Small Model

In [44]:
small_model = tf.keras.Sequential([
    layers.Lambda(lambda x: tf.expand_dims(x, axis=1)) ,
    layers.GRU(100 , activation = 'relu') , 
    layers.Dense(100 , activation = 'relu') , 
    layers.Dense(1 , activation = 'relu')
] , name = 'Small_Model')

small_model.compile(loss = tf.keras.losses.mae , optimizer = tf.keras.optimizers.Adam())

small_model.fit(x = train_data , y = train_label , epochs = 100 , batch_size = 128 , 
               validation_data = (test_data , test_label) , 
               callbacks=[create_model_checkpoint(model_name = small_model.name)])

Epoch 1/100
21/21 [==============================] - 2s 27ms/step - loss: 1290508.6250 - val_loss: 861932.3750
INFO:tensorflow:Assets written to: model_experiments\Small_Model\assets
Epoch 2/100
21/21 [==============================] - 0s 6ms/step - loss: 367507.9375 - val_loss: 354223.6250
INFO:tensorflow:Assets written to: model_experiments\Small_Model\assets
Epoch 3/100
21/21 [==============================] - 0s 6ms/step - loss: 270722.2812 - val_loss: 319959.4062
INFO:tensorflow:Assets written to: model_experiments\Small_Model\assets
Epoch 4/100
21/21 [==============================] - 0s 4ms/step - loss: 254857.1719 - val_loss: 309422.2500
INFO:tensorflow:Assets written to: model_experiments\Small_Model\assets
Epoch 5/100
21/21 [==============================] - 0s 5ms/step - loss: 255880.7656 - val_loss: 319709.0625
Epoch 6/100
21/21 [==============================] - 0s 6ms/step - loss: 244752.8125 - val_loss: 304845.3438
INFO:tensorflow:Assets written to: model_experiments\Sma

In [45]:
small_model = tf.keras.models.load_model("model_experiments/Small_Model/")
small_model.evaluate(test_data , test_label)

21/21 [==============================] - 0s 1ms/step - loss: 291816.3438


291816.34375

In [46]:
small_model_preds = make_preds(small_model , test_data)
small_model_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 120436.85, 4298189.  , 1047580.75, 3283566.2 ,  632553.  ,
        161867.02, 2402131.5 , 2703639.5 , 3241084.2 , 1990949.6 ],
      dtype=float32)>

In [47]:
small_model_error = errors(test_label , small_model_preds)
print(small_model_error)

{'MAE: ': 291816.34, 'MSE': 468630800000.0, 'RMSE': 684566.1, 'MAPE': 3976355000000.0, 'Median': 121306.69, '% error wrt median': 11.398791313171387, '% error wrt mean': 38.17374804389626, 'Min% Error': 0.0, 'Max% Error': 2515.488037109375}


## Medium Model

In [48]:
medium_model = tf.keras.Sequential([
    layers.Lambda(lambda x: tf.expand_dims(x, axis=1)) ,
    layers.GRU(300 , activation = 'relu') , 
    layers.Dense(300 , activation = 'relu') , 
    layers.Dense(300 , activation = 'relu') , 
    layers.Dense(1 , activation = 'relu')
] , name = 'Medium_Model')

medium_model.compile(loss = tf.keras.losses.mae , optimizer = tf.keras.optimizers.Adam())

medium_model.fit(x = train_data , y = train_label , epochs = 100 , batch_size = 128 , 
               validation_data = (test_data , test_label) , 
               callbacks=[create_model_checkpoint(model_name = medium_model.name)])

Epoch 1/100
21/21 [==============================] - 3s 46ms/step - loss: 553994.1875 - val_loss: 371529.3750
INFO:tensorflow:Assets written to: model_experiments\Medium_Model\assets
Epoch 2/100
21/21 [==============================] - 0s 18ms/step - loss: 275421.1562 - val_loss: 315519.4375
INFO:tensorflow:Assets written to: model_experiments\Medium_Model\assets
Epoch 3/100
21/21 [==============================] - 0s 9ms/step - loss: 252621.2344 - val_loss: 302130.0625
INFO:tensorflow:Assets written to: model_experiments\Medium_Model\assets
Epoch 4/100
21/21 [==============================] - 0s 20ms/step - loss: 240289.1719 - val_loss: 309931.5312
Epoch 5/100
21/21 [==============================] - 0s 18ms/step - loss: 240800.2656 - val_loss: 302620.0000
Epoch 6/100
21/21 [==============================] - 0s 11ms/step - loss: 241632.2656 - val_loss: 296728.2500
INFO:tensorflow:Assets written to: model_experiments\Medium_Model\assets
Epoch 7/100
21/21 [==============================

Epoch 72/100
21/21 [==============================] - 0s 10ms/step - loss: 181292.8750 - val_loss: 334421.5000
Epoch 73/100
21/21 [==============================] - 0s 10ms/step - loss: 180827.9375 - val_loss: 325392.7500
Epoch 74/100
21/21 [==============================] - 0s 9ms/step - loss: 186146.1250 - val_loss: 320633.7500
Epoch 75/100
21/21 [==============================] - 0s 9ms/step - loss: 179216.1719 - val_loss: 322654.0312
Epoch 76/100
21/21 [==============================] - 0s 13ms/step - loss: 177632.7188 - val_loss: 321789.3438
Epoch 77/100
21/21 [==============================] - 0s 13ms/step - loss: 184887.5312 - val_loss: 375437.2500
Epoch 78/100
21/21 [==============================] - 0s 13ms/step - loss: 192228.0469 - val_loss: 328352.5000
Epoch 79/100
21/21 [==============================] - 0s 10ms/step - loss: 181226.1094 - val_loss: 316194.6562
Epoch 80/100
21/21 [==============================] - 0s 13ms/step - loss: 179112.3125 - val_loss: 315478.7500
Epo

In [49]:
medium_model = tf.keras.models.load_model("model_experiments/Medium_Model/")
medium_model.evaluate(test_data , test_label)

21/21 [==============================] - 0s 2ms/step - loss: 295939.5000


295939.5

In [50]:
medium_model_preds = make_preds(medium_model , test_data)
medium_model_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 140351.34, 4195686.5 , 1012793.06, 3111692.  ,  588435.2 ,
        166307.12, 2375709.  , 2674264.2 , 3155124.2 , 1970093.1 ],
      dtype=float32)>

In [51]:
medium_model_error = errors(test_label , medium_model_preds)
print(medium_model_error)

{'MAE: ': 295939.47, 'MSE': 464838030000.0, 'RMSE': 681790.3, 'MAPE': 3200608400000.0, 'Median': 117846.61, '% error wrt median': 12.643126487731934, '% error wrt mean': 35.90661502492592, 'Min% Error': 0.0, 'Max% Error': 2108.390625}


## Large Model

In [52]:
large_model = tf.keras.Sequential([
    layers.Lambda(lambda x: tf.expand_dims(x, axis=1)) ,
    layers.GRU(512 , activation = 'relu') , 
    layers.Dense(512 , activation = 'relu') , 
    layers.Dense(512 , activation = 'relu') ,
    layers.Dense(512 , activation = 'relu') ,
    layers.Dense(1 , activation = 'relu')
] , name = 'Large_Model')

large_model.compile(loss = tf.keras.losses.mae , optimizer = tf.keras.optimizers.Adam())

large_model.fit(x = train_data , y = train_label , epochs = 100 , batch_size = 128 , 
               validation_data = (test_data , test_label) , 
               callbacks=[create_model_checkpoint(model_name = large_model.name)])

Epoch 1/100
21/21 [==============================] - 2s 46ms/step - loss: 441616.6562 - val_loss: 323460.7188
INFO:tensorflow:Assets written to: model_experiments\Large_Model\assets
Epoch 2/100
21/21 [==============================] - 1s 26ms/step - loss: 270062.9062 - val_loss: 328845.0000
Epoch 3/100
21/21 [==============================] - 1s 24ms/step - loss: 238708.0312 - val_loss: 302950.3438
INFO:tensorflow:Assets written to: model_experiments\Large_Model\assets
Epoch 4/100
21/21 [==============================] - 1s 27ms/step - loss: 249283.4062 - val_loss: 299307.7812
INFO:tensorflow:Assets written to: model_experiments\Large_Model\assets
Epoch 5/100
21/21 [==============================] - 0s 24ms/step - loss: 257007.8594 - val_loss: 295417.8125
INFO:tensorflow:Assets written to: model_experiments\Large_Model\assets
Epoch 6/100
21/21 [==============================] - 1s 29ms/step - loss: 257309.6250 - val_loss: 308396.0938
Epoch 7/100
21/21 [==============================] -

Epoch 71/100
21/21 [==============================] - 1s 25ms/step - loss: 183889.4688 - val_loss: 340597.9062
Epoch 72/100
21/21 [==============================] - 1s 27ms/step - loss: 175192.2188 - val_loss: 313779.7500
Epoch 73/100
21/21 [==============================] - 1s 24ms/step - loss: 171618.0625 - val_loss: 312768.5312
Epoch 74/100
21/21 [==============================] - 1s 27ms/step - loss: 175293.7344 - val_loss: 385203.6875
Epoch 75/100
21/21 [==============================] - 1s 26ms/step - loss: 178925.3281 - val_loss: 320924.2812
Epoch 76/100
21/21 [==============================] - 1s 28ms/step - loss: 171810.9688 - val_loss: 318472.5312
Epoch 77/100
21/21 [==============================] - 1s 30ms/step - loss: 167162.1719 - val_loss: 318014.7188
Epoch 78/100
21/21 [==============================] - 0s 24ms/step - loss: 168496.6875 - val_loss: 331437.1562
Epoch 79/100
21/21 [==============================] - 1s 24ms/step - loss: 167463.9219 - val_loss: 320328.3438
E

In [53]:
large_model = tf.keras.models.load_model("model_experiments/Large_Model/")
large_model.evaluate(test_data , test_label)

21/21 [==============================] - 0s 4ms/step - loss: 289971.7500


289971.75

In [54]:
large_model_preds = make_preds(large_model , test_data)
large_model_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 160183.72, 4393987.5 , 1051853.6 , 3290068.8 ,  582309.9 ,
        161637.78, 2425424.8 , 2741735.5 , 3254214.8 , 2005247.  ],
      dtype=float32)>

In [55]:
large_model_error = errors(test_label , large_model_preds)
print(large_model_error)

{'MAE: ': 289971.75, 'MSE': 459039000000.0, 'RMSE': 677524.2, 'MAPE': 3285335100000.0, 'Median': 112827.92, '% error wrt median': 11.359111785888672, '% error wrt mean': 42.61673978938017, 'Min% Error': 0.0, 'Max% Error': 2509.044189453125}


In [56]:
import matplotlib.pyplot as plt
# Create a function to plot time series data
def plot_time_series(timesteps, values, format='.', start=0, end=None, label=None):
  # Plot the series
    plt.plot(timesteps[start:end], values[start:end], format, label=label)
    plt.xlabel("Time")
    plt.ylabel("Price")
    if label:
        plt.legend(fontsize=14) # make label bigger
    plt.grid(False)

In [57]:
def upper_lower(y_true , y_pred):
    y_true = tf.cast(y_true, dtype=tf.float32)
    y_pred = tf.cast(y_pred, dtype=tf.float32)
    upper = y_pred + (y_pred*15/100)
    lower = y_pred - (y_pred*15/100)
    return upper , lower

In [161]:
upper , lower = upper_lower(test_label , combined_model_preds)
dictionary = {'True Value' : test_label , 'Prediction' : combined_model_preds , 'Upper' : upper , 'Lower' : lower}
datas = pd.DataFrame(dictionary)
datas.head()

True Value    Prediction         Upper         Lower
0    88287.00  1.384496e+05  1.592170e+05  1.176821e+05
1  4399137.02  4.363432e+06  5.017946e+06  3.708917e+06
2  1007368.34  1.035585e+06  1.190923e+06  8.802476e+05
3  3480342.96  3.099590e+06  3.564529e+06  2.634652e+06
4  2186020.23  6.116046e+05  7.033453e+05  5.198639e+05

In [162]:
for i in range(len(datas)):
    if(datas.iloc[i].loc['Upper'] < datas.iloc[i].loc['True Value']):
        datas.loc[i , 'Outlier'] = 1
    
    elif(datas.iloc[i].loc['Lower'] > datas.iloc[i].loc['True Value']):
        datas.loc[i , 'Outlier'] = -1
        
datas.head()

True Value    Prediction         Upper         Lower  Outlier
0    88287.00  1.384496e+05  1.592170e+05  1.176821e+05     -1.0
1  4399137.02  4.363432e+06  5.017946e+06  3.708917e+06      NaN
2  1007368.34  1.035585e+06  1.190923e+06  8.802476e+05      NaN
3  3480342.96  3.099590e+06  3.564529e+06  2.634652e+06      NaN
4  2186020.23  6.116046e+05  7.033453e+05  5.198639e+05      1.0

In [163]:
up = datas.where(datas['Outlier'] > 0)
up.dropna(subset = ["Outlier"] , inplace=True)
print(len(up))

162


In [164]:
down = datas.where(datas['Outlier'] < 0)
down.dropna(subset = ["Outlier"], inplace=True)
print(len(down))

151


## Stack model

In [160]:
combined_model_preds = (small_model_preds + medium_model_preds + large_model_preds) / 3

array([[6.02777060e+05, 2.74240000e+05, 1.55352260e+06, ...,
        4.20590800e+06, 6.88134400e+06, 6.10144400e+06],
       [1.78063200e+05, 2.29100000e+06, 0.00000000e+00, ...,
        1.65729000e+06, 1.84000000e+03, 1.80000000e+03],
       [2.16684000e+05, 0.00000000e+00, 1.07945000e+05, ...,
        2.12734200e+05, 0.00000000e+00, 1.36696800e+05],
       ...,
       [3.20160996e+06, 2.89466561e+06, 2.13520424e+06, ...,
        3.66557960e+06, 3.71931443e+06, 3.23460348e+06],
       [9.18454080e+05, 8.74652700e+05, 4.64518930e+05, ...,
        1.00193220e+06, 1.00426506e+06, 8.83992330e+05],
       [9.71937060e+05, 3.65951800e+05, 1.42128060e+05, ...,
        4.77106230e+05, 2.53897860e+05, 5.21142970e+05]])

## Normalise data

In [58]:
maxi = tf.math.reduce_max(full_window[: , :7])
mini = tf.math.reduce_min(full_window[: , :7])
full_try = full_window[: , :7] / (maxi - mini)

full_try[:5]

<tf.Tensor: shape=(5, 7), dtype=float64, numpy=
array([[5.21636963e-02, 2.37324428e-02, 1.34440221e-01, 3.32599662e-01,
        3.63974879e-01, 5.95504312e-01, 5.28012582e-01],
       [1.54094031e-02, 1.98260744e-01, 0.00000000e+00, 2.20134330e-03,
        1.43420143e-01, 1.59231675e-04, 1.55770117e-04],
       [1.87516067e-02, 0.00000000e+00, 9.34144740e-03, 0.00000000e+00,
        1.84097952e-02, 0.00000000e+00, 1.18295981e-02],
       [4.45817695e-01, 3.87977008e-01, 4.97659776e-01, 5.05399469e-01,
        4.84661820e-01, 4.37597944e-01, 3.95666078e-01],
       [2.23312309e-01, 1.80422237e-01, 2.23787475e-01, 2.57867460e-01,
        2.04827538e-01, 2.04329329e-01, 1.93576384e-01]])>

In [59]:
full_window[: , 7:]

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [60]:
combine_data = tf.concat([full_try , full_window[: , 7:]] , 1)
combine_data[:3]

<tf.Tensor: shape=(3, 47), dtype=float64, numpy=
array([[5.21636963e-02, 2.37324428e-02, 1.34440221e-01, 3.32599662e-01,
        3.63974879e-01, 5.95504312e-01, 5.28012582e-01, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.54094031e-02, 1.98260744e-01, 0.00000000e+00, 2.20134330e-03,
        1.43420143e-01, 1.5923

In [61]:
combine_label = full_label / (maxi - mini)

In [62]:
train_data , test_data , train_label , test_label = train_test_split(combine_data , combine_label)
test_data[:3] , test_label[:3]

(<tf.Tensor: shape=(3, 47), dtype=float64, numpy=
 array([[0.00826229, 0.03193741, 0.01266523, 0.01678792, 0.00957366,
         0.00464406, 0.00633839, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 1.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ],
        [0.35420043, 0.37005743, 0.2501399 , 0.37775669, 0.39423797,
         0.32434376, 0.38417307, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 1.        , 0.        ,
         0.        

## Tiny Model

In [84]:
from tensorflow.keras import layers

tiny_model = tf.keras.Sequential([
    layers.Lambda(lambda x: tf.expand_dims(x, axis=1)) ,
    layers.GRU(100 , activation = 'relu') , 
    layers.Dense(1 , activation = 'relu')
] , name = 'Tiny_Model')

tiny_model.compile(loss = tf.keras.losses.mae , optimizer = tf.keras.optimizers.Adam())

tiny_model.fit(x = train_data , y = train_label , epochs = 300 , batch_size = 128 , 
               validation_data = (test_data , test_label) , 
               callbacks=[create_model_checkpoint(model_name=tiny_model.name)])

Epoch 1/300
21/21 [==============================] - 1s 13ms/step - loss: 0.0698 - val_loss: 0.0368
INFO:tensorflow:Assets written to: model_experiments\Tiny_Model\assets
Epoch 2/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0262 - val_loss: 0.0311
INFO:tensorflow:Assets written to: model_experiments\Tiny_Model\assets
Epoch 3/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0228 - val_loss: 0.0292
INFO:tensorflow:Assets written to: model_experiments\Tiny_Model\assets
Epoch 4/300
21/21 [==============================] - 0s 3ms/step - loss: 0.0223 - val_loss: 0.0290
INFO:tensorflow:Assets written to: model_experiments\Tiny_Model\assets
Epoch 5/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0220 - val_loss: 0.0289
INFO:tensorflow:Assets written to: model_experiments\Tiny_Model\assets
Epoch 6/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0217 - val_loss: 0.0295
Epoch 7/300
21/21 [==============================]

21/21 [==============================] - 0s 2ms/step - loss: 0.0185 - val_loss: 0.0312
Epoch 156/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0181 - val_loss: 0.0296
Epoch 157/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0182 - val_loss: 0.0301
Epoch 158/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0183 - val_loss: 0.0300
Epoch 159/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0183 - val_loss: 0.0297
Epoch 160/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0182 - val_loss: 0.0299
Epoch 161/300
21/21 [==============================] - 0s 3ms/step - loss: 0.0180 - val_loss: 0.0280
Epoch 162/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0182 - val_loss: 0.0272
INFO:tensorflow:Assets written to: model_experiments\Tiny_Model\assets
Epoch 163/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0182 - val_loss: 0.0298
Epoch 164/300
21/21 [=============

Epoch 235/300
21/21 [==============================] - 0s 3ms/step - loss: 0.0175 - val_loss: 0.0297
Epoch 236/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0175 - val_loss: 0.0279
Epoch 237/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0176 - val_loss: 0.0286
Epoch 238/300
21/21 [==============================] - 0s 3ms/step - loss: 0.0177 - val_loss: 0.0283
Epoch 239/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0177 - val_loss: 0.0273
Epoch 240/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0175 - val_loss: 0.0306
Epoch 241/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0177 - val_loss: 0.0312
Epoch 242/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0175 - val_loss: 0.0300
Epoch 243/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0173 - val_loss: 0.0294
Epoch 244/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0175 - val_los

In [85]:
tiny_model = tf.keras.models.load_model("model_experiments/Tiny_Model/")
tiny_model.evaluate(test_data , test_label)

21/21 [==============================] - 0s 514us/step - loss: 0.0272


0.0271619725972414

In [86]:
tiny_model_preds = make_preds(tiny_model , test_data)
tiny_model_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.        , 0.3436861 , 0.09206378, 0.27256387, 0.04556163,
       0.01453357, 0.2024903 , 0.21355343, 0.28043923, 0.1449376 ],
      dtype=float32)>

In [87]:
tiny_model_preds = tf.nn.relu(tiny_model_preds)

In [88]:
tiny_model_error = errors(test_label , tiny_model_preds)
print(tiny_model_error)

{'MAE: ': 0.027161973, 'MSE': 0.0038540538, 'RMSE': 0.062081028, 'MAPE': 156704.77, 'Median': 0.010800427, '% error wrt median': 12.785541534423828, '% error wrt mean': 35.91157804216103, 'Min% Error': 0.0, 'Max% Error': 1089.7802734375}


## Small Model

In [89]:
small_model = tf.keras.Sequential([
    layers.Lambda(lambda x: tf.expand_dims(x, axis=1)) ,
    layers.GRU(100 , activation = 'relu') , 
    layers.Dense(100 , activation = 'relu') , 
    layers.Dense(1 , activation = 'relu')
] , name = 'Small_Model')

small_model.compile(loss = tf.keras.losses.mae , optimizer = tf.keras.optimizers.Adam())

small_model.fit(x = train_data , y = train_label , epochs = 300 , batch_size = 128 , 
               validation_data = (test_data , test_label) , 
               callbacks=[create_model_checkpoint(model_name = small_model.name)])

Epoch 1/300
21/21 [==============================] - 1s 15ms/step - loss: 0.0609 - val_loss: 0.0351
INFO:tensorflow:Assets written to: model_experiments\Small_Model\assets
Epoch 2/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0250 - val_loss: 0.0296
INFO:tensorflow:Assets written to: model_experiments\Small_Model\assets
Epoch 3/300
21/21 [==============================] - 0s 3ms/step - loss: 0.0227 - val_loss: 0.0284
INFO:tensorflow:Assets written to: model_experiments\Small_Model\assets
Epoch 4/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0226 - val_loss: 0.0296
Epoch 5/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0223 - val_loss: 0.0282
INFO:tensorflow:Assets written to: model_experiments\Small_Model\assets
Epoch 6/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0220 - val_loss: 0.0288
Epoch 7/300
21/21 [==============================] - 0s 3ms/step - loss: 0.0217 - val_loss: 0.0293
Epoch 8/300
21/21 

21/21 [==============================] - 0s 2ms/step - loss: 0.0175 - val_loss: 0.0314
Epoch 158/300
21/21 [==============================] - 0s 3ms/step - loss: 0.0173 - val_loss: 0.0289
Epoch 159/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0169 - val_loss: 0.0314
Epoch 160/300
21/21 [==============================] - 0s 3ms/step - loss: 0.0170 - val_loss: 0.0316
Epoch 161/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0170 - val_loss: 0.0312
Epoch 162/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0174 - val_loss: 0.0272
Epoch 163/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0169 - val_loss: 0.0298
Epoch 164/300
21/21 [==============================] - 0s 3ms/step - loss: 0.0171 - val_loss: 0.0278
Epoch 165/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0172 - val_loss: 0.0287
Epoch 166/300
21/21 [==============================] - 0s 2ms/step - loss: 0.0168 - val_loss: 0.0299
Epoc

In [90]:
small_model = tf.keras.models.load_model("model_experiments/Small_Model/")
small_model.evaluate(test_data , test_label)

21/21 [==============================] - 0s 851us/step - loss: 0.0268


0.026753311976790428

In [91]:
small_model_preds = make_preds(small_model , test_data)
small_model_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.        , 0.35321793, 0.08522871, 0.28039318, 0.04297823,
       0.01856471, 0.21072303, 0.21429683, 0.2752472 , 0.15966758],
      dtype=float32)>

In [108]:
small_model_preds = tf.nn.relu(small_model_preds)

In [109]:
small_model_error = errors(test_label , small_model_preds)
print(small_model_error)

{'MAE: ': 0.026753316, 'MSE': 0.0038803536, 'RMSE': 0.062292486, 'MAPE': 284445.28, 'Median': 0.011630249, '% error wrt median': 12.981523513793945, '% error wrt mean': 33.71651765200797, 'Min% Error': 0.0, 'Max% Error': 453.2398681640625}


## Medium Model

In [93]:
medium_model = tf.keras.Sequential([
    layers.Lambda(lambda x: tf.expand_dims(x, axis=1)) ,
    layers.GRU(300 , activation = 'relu') , 
    layers.Dense(300 , activation = 'relu') , 
    layers.Dense(300 , activation = 'relu') , 
    layers.Dense(1 , activation = 'relu')
] , name = 'Medium_Model')

medium_model.compile(loss = tf.keras.losses.mae , optimizer = tf.keras.optimizers.Adam())

medium_model.fit(x = train_data , y = train_label , epochs = 300 , batch_size = 128 , 
               validation_data = (test_data , test_label) , 
               callbacks=[create_model_checkpoint(model_name = medium_model.name)])

Epoch 1/300
21/21 [==============================] - 2s 19ms/step - loss: 0.0497 - val_loss: 0.0374
INFO:tensorflow:Assets written to: model_experiments\Medium_Model\assets
Epoch 2/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0257 - val_loss: 0.0294
INFO:tensorflow:Assets written to: model_experiments\Medium_Model\assets
Epoch 3/300
21/21 [==============================] - 0s 8ms/step - loss: 0.0234 - val_loss: 0.0284
INFO:tensorflow:Assets written to: model_experiments\Medium_Model\assets
Epoch 4/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0222 - val_loss: 0.0288
Epoch 5/300
21/21 [==============================] - 0s 6ms/step - loss: 0.0214 - val_loss: 0.0278
INFO:tensorflow:Assets written to: model_experiments\Medium_Model\assets
Epoch 6/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0212 - val_loss: 0.0279
Epoch 7/300
21/21 [==============================] - 0s 6ms/step - loss: 0.0216 - val_loss: 0.0316
Epoch 8/300
21

21/21 [==============================] - 0s 7ms/step - loss: 0.0150 - val_loss: 0.0296
Epoch 158/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0149 - val_loss: 0.0293
Epoch 159/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0147 - val_loss: 0.0277
Epoch 160/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0151 - val_loss: 0.0282
Epoch 161/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0157 - val_loss: 0.0289
Epoch 162/300
21/21 [==============================] - 0s 8ms/step - loss: 0.0152 - val_loss: 0.0273
Epoch 163/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0148 - val_loss: 0.0300
Epoch 164/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0150 - val_loss: 0.0282
Epoch 165/300
21/21 [==============================] - 0s 8ms/step - loss: 0.0147 - val_loss: 0.0294
Epoch 166/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0149 - val_loss: 0.0284
Epoc

Epoch 237/300
21/21 [==============================] - 0s 8ms/step - loss: 0.0137 - val_loss: 0.0282
Epoch 238/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0136 - val_loss: 0.0268
Epoch 239/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0137 - val_loss: 0.0302
Epoch 240/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0135 - val_loss: 0.0269
Epoch 241/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0137 - val_loss: 0.0274
Epoch 242/300
21/21 [==============================] - 0s 7ms/step - loss: 0.0134 - val_loss: 0.0281
Epoch 243/300
21/21 [==============================] - 0s 8ms/step - loss: 0.0140 - val_loss: 0.0327
Epoch 244/300
21/21 [==============================] - 0s 8ms/step - loss: 0.0148 - val_loss: 0.0269
Epoch 245/300
21/21 [==============================] - 0s 8ms/step - loss: 0.0143 - val_loss: 0.0263
Epoch 246/300
21/21 [==============================] - 0s 8ms/step - loss: 0.0142 - val_los

In [94]:
medium_model = tf.keras.models.load_model("model_experiments/Medium_Model/")
medium_model.evaluate(test_data , test_label)

21/21 [==============================] - 0s 2ms/step - loss: 0.0254


0.02542370930314064

In [95]:
medium_model_preds = make_preds(medium_model , test_data)
medium_model_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.00800249, 0.35307908, 0.08953201, 0.2892795 , 0.0435142 ,
       0.01659892, 0.21504202, 0.20584637, 0.27860004, 0.15738466],
      dtype=float32)>

In [110]:
medium_model_preds = tf.nn.relu(medium_model_preds)

In [111]:
medium_model_error = errors(test_label , medium_model_preds)
print(medium_model_error)

{'MAE: ': 0.025423711, 'MSE': 0.0038542124, 'RMSE': 0.0620823, 'MAPE': 328252.72, 'Median': 0.008705486, '% error wrt median': 10.866072654724121, '% error wrt mean': 43.859119025358396, 'Min% Error': 0.0, 'Max% Error': 5776.53662109375}


## Large Model

In [97]:
large_model = tf.keras.Sequential([
    layers.Lambda(lambda x: tf.expand_dims(x, axis=1)) ,
    layers.GRU(512 , activation = 'relu') , 
    layers.Lambda(lambda x: tf.expand_dims(x, axis=1)) ,
    layers.Dense(512 , activation = 'relu') , 
    layers.Dense(512 , activation = 'relu') ,
    layers.Dense(512 , activation = 'relu') ,
    layers.Dense(1 , activation = 'relu')
] , name = 'Large_Model')

large_model.compile(loss = tf.keras.losses.mae , optimizer = tf.keras.optimizers.Adam())

large_model.fit(x = train_data , y = train_label , epochs = 300 , batch_size = 128 , 
               validation_data = (test_data , test_label) , 
               callbacks=[create_model_checkpoint(model_name = large_model.name)])

Epoch 1/300
21/21 [==============================] - 2s 36ms/step - loss: 0.0465 - val_loss: 0.0296
INFO:tensorflow:Assets written to: model_experiments\Large_Model\assets
Epoch 2/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0242 - val_loss: 0.0299
Epoch 3/300
21/21 [==============================] - 0s 23ms/step - loss: 0.0224 - val_loss: 0.0295
INFO:tensorflow:Assets written to: model_experiments\Large_Model\assets
Epoch 4/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0228 - val_loss: 0.0404
Epoch 5/300
21/21 [==============================] - 0s 21ms/step - loss: 0.0219 - val_loss: 0.0283
INFO:tensorflow:Assets written to: model_experiments\Large_Model\assets
Epoch 6/300
21/21 [==============================] - 0s 21ms/step - loss: 0.0212 - val_loss: 0.0278
INFO:tensorflow:Assets written to: model_experiments\Large_Model\assets
Epoch 7/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0209 - val_loss: 0.0275
INFO:tensorf

Epoch 76/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0193 - val_loss: 0.0316
Epoch 77/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0176 - val_loss: 0.0279
Epoch 78/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0173 - val_loss: 0.0287
Epoch 79/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0176 - val_loss: 0.0292
Epoch 80/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0177 - val_loss: 0.0346
Epoch 81/300
21/21 [==============================] - 0s 21ms/step - loss: 0.0185 - val_loss: 0.0305
Epoch 82/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0177 - val_loss: 0.0265
Epoch 83/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0179 - val_loss: 0.0272
Epoch 84/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0177 - val_loss: 0.0301
Epoch 85/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0173 - val_los

21/21 [==============================] - 0s 20ms/step - loss: 0.0137 - val_loss: 0.0289
Epoch 237/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0139 - val_loss: 0.0297
Epoch 238/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0142 - val_loss: 0.0274
Epoch 239/300
21/21 [==============================] - 0s 21ms/step - loss: 0.0140 - val_loss: 0.0346
Epoch 240/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0145 - val_loss: 0.0322
Epoch 241/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0154 - val_loss: 0.0267
Epoch 242/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0145 - val_loss: 0.0294
Epoch 243/300
21/21 [==============================] - 0s 21ms/step - loss: 0.0144 - val_loss: 0.0263
Epoch 244/300
21/21 [==============================] - 0s 20ms/step - loss: 0.0144 - val_loss: 0.0281
Epoch 245/300
21/21 [==============================] - 0s 21ms/step - loss: 0.0137 - val_loss: 0

In [98]:
large_model = tf.keras.models.load_model("model_experiments/Large_Model/")
large_model.evaluate(test_data , test_label)

21/21 [==============================] - 0s 4ms/step - loss: 0.0257


0.02573590911924839

In [99]:
large_model_preds = make_preds(large_model , test_data)
large_model_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.0071335 , 0.3590504 , 0.09298075, 0.3005424 , 0.03535212,
       0.01569966, 0.22187753, 0.24166933, 0.29623926, 0.16588236],
      dtype=float32)>

In [112]:
large_model_preds = tf.nn.relu(large_model_preds)

In [113]:
large_model_error = errors(test_label , large_model_preds)
print(large_model_error)

{'MAE: ': 0.025735911, 'MSE': 0.0038146512, 'RMSE': 0.061762862, 'MAPE': 314445.25, 'Median': 0.009154161, '% error wrt median': 12.58082914352417, '% error wrt mean': 29.056579712664686, 'Min% Error': 0.0, 'Max% Error': 1043.606201171875}


In [119]:
combined_model_preds = (medium_model_preds + tiny_model_preds + large_model_preds + small_model_preds) / 4
upper , lower = upper_lower(test_label , combined_model_preds)
dictionary = {'True Value' : test_label , 'Prediction' : medium_model_preds , 'Upper' : upper , 'Lower' : lower}
datas = pd.DataFrame(dictionary)

for i in range(len(datas)):
    if(datas.iloc[i].loc['Upper'] < datas.iloc[i].loc['True Value']):
        datas.loc[i , 'Outlier'] = 1
    
    elif(datas.iloc[i].loc['Lower'] > datas.iloc[i].loc['True Value']):
        datas.loc[i , 'Outlier'] = -1

up = datas.where(datas['Outlier'] > 0)
up.dropna(subset = ["Outlier"] , inplace=True)
print(len(up))

down = datas.where(datas['Outlier'] < 0)
down.dropna(subset = ["Outlier"], inplace=True)
print(len(down))

212
109
